-- INSERT INTO MEMBER (USERNAME, PASSWORD) VALUES('ADMIN', 'ADMIN');
INSERT INTO TERMS_OF_SERVICE(ID, TITLE, CONTENT, NEED_AGREEMENT) VALUES(1, "TITLE1", "CONTENT1", TRUE);
INSERT INTO TERMS_OF_SERVICE(ID, TITLE, CONTENT, NEED_AGREEMENT) VALUES(2, "TITLE2", "CONTENT2", TRUE);

